export const basicPathnameArr = [
  '/',
  '/pl',
  '/ua',
  '/en',
  // '/pl/montessori',
  // '/ua/montessori',
  // '/en/montessori',
  // '/pl/bilingual',
  // '/ua/bilingual',
  // '/en/bilingual',
  // '/pl/party',
  // '/ua/party',
  // '/en/party',
  // '/pl/workshops',
  // '/ua/workshops',
  // '/en/workshops',
  '/pl/cookies-polityka-ciasteczek',
  '/ua/cookies-polityka-ciasteczek',
  '/en/cookies-polityka-ciasteczek',
  '/pl/galeria',
  '/ua/galeria',
  '/en/galeria',
  '/pl/kontakt',
  '/ua/kontakt',
  '/en/kontakt',
  '/pl/lato',
  '/ua/lato',
  '/en/lato',
  '/pl/o-nas',
  '/ua/o-nas',
  '/en/o-nas',
  '/pl/pl/rotator/labokids-2',
  '/ua/pl/rotator/labokids-2',
  '/en/pl/rotator/labokids-2',
  '/pl/search',
  '/ua/search',
  '/en/search',
  '/pl/urodzinki-nowa-sala',
  '/ua/urodzinki-nowa-sala',
  '/en/urodzinki-nowa-sala',
  '/pl/przedszkole/panel-rodzica',
  '/ua/przedszkole/panel-rodzica',
  '/en/przedszkole/panel-rodzica',
  '/pl/przedszkole/rekrutacja',
  '/ua/przedszkole/rekrutacja',
  '/en/przedszkole/rekrutacja',
  '/pl/przedszkole/menu',
  '/ua/przedszkole/menu',
  '/en/przedszkole/menu',
  '/pl/przedszkole/aktualnosci',
  '/ua/przedszkole/aktualnosci',
  '/en/przedszkole/aktualnosci',
];
